---
- name: 'Install dependency packages'
  action: apt pkg={{item}} state=installed
  with_items:
    - libxml2
    - libxml2-dev
    - libncurses5
    - libncurses5-dev
    - sqlite
    - libsqlite0-dev
    - sqlite3
    - libsqlite3-dev
    - libjansson-dev
    - uuid
    - uuid-dev
    - mysql-client
    - libmysqlclient-dev
    - libxml2
    - libxml2-dev
    - libssl-dev
    - postgresql-client
    - postgresql-client-common
    - libperl-dev
    - libdbi-perl
    - libdbd-mysql-perl
    - libdbd-pg-perl
    - libsrtp0
    - libsrtp0-dev
    - unixodbc
    - unixodbc-dev
    - ngrep
    - libneon27
    - libneon27-dev
    - libical-dev
    - libltdl-dev
    - libiksemel-dev
    - libodbc1
    - speex
    - automake
    - binutils-dev
    - doxygen
    - freetds-dev
    - libasound2-dev
    - libbluetooth-dev
    - libc-client2007e-dev
    - libcorosync-dev
    - libcurl4-openssl-dev
    - libedit-dev
    - libgsm1-dev
    - libical-dev
    - libjack-dev
    - libldap2-dev
    - liblua5.1-0-dev
    - libnewt-dev
    - libogg-dev
    - libopenh323-dev
    - libpopt-dev
    - libradiusclient-ng-dev
    - libresample1-dev
    - libsnmp-dev
    - libspandsp-dev
    - libspeex-dev
    - libspeexdsp-dev
    - libusb-dev
    - libvorbis-dev
    - libxslt1-dev
    - portaudio19-dev
    - subversion
